const data = [
  {
    id: 289,
    name: "Lionel Messi",
    name_short: "L. Messi",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/lionel-messi.png",
    position: "F",
    age: 36,
    nationality_code: "ARG",
    flag: "argentina",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 1327,
    name: "Sergio Ramos",
    name_short: "S. Ramos",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/sergio-ramos.png",
    position: "D",
    age: 37,
    nationality_code: "ESP",
    flag: "spain",
    rating: 61.3,
    ability: [
      {
        name: "Attacking",
        value: 28,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 28,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 95,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 28,
        full_average: 50,
      },
    ],
  },
  {
    id: 85744,
    name: "Gianluigi Donnarumma",
    name_short: "G. Donnarumma",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/gianluigi-donnarumma.png",
    position: "G",
    age: 24,
    nationality_code: "ITA",
    flag: "italy",
    rating: 69.3,
    ability: [
      {
        name: "Aerial",
        value: 28,
        full_average: 64,
      },
      {
        name: "Anticipation",
        value: 28,
        full_average: 52,
      },
      {
        name: "Saves",
        value: 95,
        full_average: 32,
      },
      {
        name: "Ball distribution",
        value: 73,
        full_average: 45,
      },
      {
        name: "Tactical",
        value: 28,
        full_average: 50,
      },
    ],
  },
  {
    id: 1320,
    name: "Luka Modrić",
    name_short: "L. Modrić",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/luka-modric.png",
    position: "M",
    age: 36,
    nationality_code: "CRO",
    flag: "croatia",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 987987,
    name: "Cristiano Ronaldo",
    name_short: "C. Ronaldo",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/cristiano-ronaldo.png",
    position: "F",
    age: 36,
    nationality_code: "POR",
    flag: "portugal",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 555,
    name: "Neymar JR",
    name_short: "Neymar JR",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/neymar-jr.png",
    position: "F",
    age: 36,
    nationality_code: "BRA",
    flag: "brazil",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 666,
    name: "Kylian Mbappé",
    name_short: "K. Mbappé",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/kylian-mbappe.png",
    position: "F",
    age: 36,
    nationality_code: "FRA",
    flag: "france",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 777,
    name: "Kevin De Bruyne",
    name_short: "K. De Bruyne",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/kevin-de-bruyne.png",
    position: "M",
    age: 36,
    nationality_code: "BEL",
    flag: "belgium",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 888,
    name: "Jan Oblak",
    name_short: "J. Oblak",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/jan-oblak.png",
    position: "G",
    age: 36,
    nationality_code: "SVN",
    flag: "slovenia",
    rating: 79.7,
    ability: [
      {
        name: "Aerial",
        value: 95,
        full_average: 64,
      },
      {
        name: "Anticipation",
        value: 94,
        full_average: 52,
      },
      {
        name: "Saves",
        value: 28,
        full_average: 32,
      },
      {
        name: "Ball distribution",
        value: 73,
        full_average: 45,
      },
      {
        name: "Tactical",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 999,
    name: "Rodrigo Hernández",
    name_short: "Rodri",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/rodrigo-hernandez.png",
    position: "M",
    age: 36,
    nationality_code: "ESP",
    flag: "spain",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 1010,
    name: "Pedro González López",
    name_short: "Pedri",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/pedro-gonzalez-lopez.png",
    position: "M",
    age: 36,
    nationality_code: "ESP",
    flag: "spain",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 1111,
    name: "Dani Carvajal",
    name_short: "D. Carvajal",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/dani-carvajal.png",
    position: "D",
    age: 36,
    nationality_code: "ESP",
    flag: "spain",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 1212,
    name: "Raphaël Varane",
    name_short: "R. Varane",
    has_photo: true,
    photo: "https://tipsscore.com/resb/player/raphael-varane.png",
    position: "D",
    age: 36,
    nationality_code: "FRA",
    flag: "france",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
  {
    id: 1313,
    name: "Marcelo Vieira da Silva Júnior",
    name_short: "Marcelo",
    has_photo: true,
    photo:
      "https://tipsscore.com/resb/player/marcelo-vieira-da-silva-junior.png",
    position: "D",
    age: 36,
    nationality_code: "BRA",
    flag: "brazil",
    rating: 79.7,
    ability: [
      {
        name: "Attacking",
        value: 95,
        full_average: 64,
      },
      {
        name: "Technical",
        value: 94,
        full_average: 52,
      },
      {
        name: "Defending",
        value: 28,
        full_average: 32,
      },
      {
        name: "Tactical",
        value: 73,
        full_average: 45,
      },
      {
        name: "Creativity",
        value: 91,
        full_average: 50,
      },
    ],
  },
];

export default data;
